create table products (
    id       bigint generated by default as identity primary key,
    name     varchar(100) not null,
    price    bigint       not null,
    stock    integer      not null,
    reserved integer      not null default 0,
    constraint ck_products_quantities check (stock >= 0 and reserved >= 0 and reserved <= stock)
);

create table coupons (
    id                  bigint generated by default as identity primary key,
    code                varchar(20) not null unique,
    type                varchar(10) not null,
    discount_value      bigint      not null,
    min_order_amount    bigint      not null,
    max_discount_amount bigint,
    total_quantity      integer     not null,
    used_count          integer     not null default 0,
    valid_from          timestamptz not null,
    valid_until         timestamptz not null,
    constraint ck_coupons_usage check (used_count >= 0 and used_count <= total_quantity)
);

create table orders (
    id          bigint generated by default as identity primary key,
    user_id     varchar(50)  not null,
    status      varchar(20)  not null,
    coupon_code varchar(20) references coupons (code),
    subtotal    bigint       not null,
    discount    bigint       not null,
    total_price bigint       not null,
    payment_id  varchar(100),
    created_at  timestamptz  not null,
    expires_at  timestamptz  not null,
    paid_at     timestamptz
);

create index ix_orders_created on orders (created_at desc, id desc);
create index ix_orders_user_created on orders (user_id, created_at desc, id desc);
create index ix_orders_pending_expiry on orders (expires_at) where status = 'PENDING_PAYMENT';
-- 한 사용자는 같은 쿠폰을 동시에 하나의 주문에서만 사용할 수 있다 (R2.5 최후 방어선)
create unique index ux_orders_active_coupon_use on orders (user_id, coupon_code)
    where coupon_code is not null and status in ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED');

create table order_items (
    id         bigint generated by default as identity primary key,
    order_id   bigint  not null references orders (id),
    product_id bigint  not null references products (id),
    quantity   integer not null,
    unit_price bigint  not null
);

create index ix_order_items_order on order_items (order_id);

create table idempotency_keys (
    scope             varchar(20) not null,
    idempotency_key   varchar(64) not null,
    fingerprint       varchar(64) not null,
    status            varchar(20) not null,
    response_status   integer,
    response_body     text,
    response_location text,
    created_at        timestamptz not null default now(),
    primary key (scope, idempotency_key)
);
