spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  flyway:
    enabled: true
  jackson:
    deserialization:
      accept-float-as-int: false
    mapper:
      allow-coercion-of-scalars: false

server:
  port: 8080
