-- V1__init.sql : order-payment 초기 스키마

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    price       BIGINT       NOT NULL,
    stock       INTEGER      NOT NULL,
    reserved    INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_products_price    CHECK (price BETWEEN 1 AND 10000000),
    CONSTRAINT ck_products_stock    CHECK (stock >= 0),
    CONSTRAINT ck_products_reserved CHECK (reserved >= 0 AND reserved <= stock)
);

CREATE TABLE coupons (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(20)  NOT NULL,
    discount_type        VARCHAR(10)  NOT NULL,
    discount_value       BIGINT       NOT NULL,
    min_order_amount     BIGINT       NOT NULL DEFAULT 0,
    max_discount_amount  BIGINT,
    total_quantity       BIGINT       NOT NULL,
    used_count           BIGINT       NOT NULL DEFAULT 0,
    valid_from           TIMESTAMPTZ  NOT NULL,
    valid_until          TIMESTAMPTZ  NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_coupons_code           UNIQUE (code),
    CONSTRAINT ck_coupons_code           CHECK (code ~ '^[A-Z0-9]{4,20}$'),
    CONSTRAINT ck_coupons_type           CHECK (discount_type IN ('FIXED', 'RATE')),
    CONSTRAINT ck_coupons_value          CHECK (discount_value >= 1
                                                AND (discount_type <> 'RATE' OR discount_value <= 100)),
    CONSTRAINT ck_coupons_min_order      CHECK (min_order_amount >= 0),
    CONSTRAINT ck_coupons_max_discount   CHECK (max_discount_amount IS NULL OR max_discount_amount >= 1),
    CONSTRAINT ck_coupons_total_quantity CHECK (total_quantity >= 1),
    CONSTRAINT ck_coupons_used_count     CHECK (used_count >= 0 AND used_count <= total_quantity),
    CONSTRAINT ck_coupons_valid_range    CHECK (valid_from < valid_until)
);

CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(50)  NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    coupon_code  VARCHAR(20),
    subtotal     BIGINT       NOT NULL,
    discount     BIGINT       NOT NULL,
    total_price  BIGINT       NOT NULL,
    payment_id   VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    paid_at      TIMESTAMPTZ,
    CONSTRAINT fk_orders_coupon_code FOREIGN KEY (coupon_code) REFERENCES coupons (code),
    CONSTRAINT ck_orders_status CHECK (status IN (
        'PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED', 'EXPIRED',
        'CANCELLED', 'REFUNDED', 'SHIPPED', 'DELIVERED')),
    CONSTRAINT ck_orders_amounts CHECK (
        subtotal >= 0 AND discount >= 0 AND discount <= subtotal
        AND total_price = subtotal - discount),
    CONSTRAINT ck_orders_expires CHECK (expires_at >= created_at)
);

CREATE UNIQUE INDEX uk_orders_coupon_user_active
    ON orders (coupon_code, user_id)
    WHERE coupon_code IS NOT NULL
      AND status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED');

CREATE INDEX ix_orders_created_id        ON orders (created_at DESC, id DESC);
CREATE INDEX ix_orders_user_created_id   ON orders (user_id, created_at DESC, id DESC);
CREATE INDEX ix_orders_status_created_id ON orders (status, created_at DESC, id DESC);
CREATE INDEX ix_orders_pending_expires   ON orders (expires_at) WHERE status = 'PENDING_PAYMENT';

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT  NOT NULL,
    line_no     INTEGER NOT NULL,
    product_id  BIGINT  NOT NULL,
    quantity    INTEGER NOT NULL,
    unit_price  BIGINT  NOT NULL,
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_order_items_order_line    UNIQUE (order_id, line_no),
    CONSTRAINT uk_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_line_no    CHECK (line_no >= 0),
    CONSTRAINT ck_order_items_quantity   CHECK (quantity BETWEEN 1 AND 1000),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 1)
);

CREATE TABLE idempotency_keys (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope              VARCHAR(20)  NOT NULL,
    idem_key           VARCHAR(64)  NOT NULL,
    request_hash       VARCHAR(64)  NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    response_status    INTEGER,
    response_body      TEXT,
    response_location  VARCHAR(255),
    created_at         TIMESTAMPTZ  NOT NULL,
    completed_at       TIMESTAMPTZ,
    CONSTRAINT uk_idempotency_scope_key UNIQUE (scope, idem_key),
    CONSTRAINT ck_idempotency_scope  CHECK (scope IN ('CREATE_ORDER', 'PAY_ORDER')),
    CONSTRAINT ck_idempotency_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_idempotency_completed CHECK (
        status <> 'COMPLETED'
        OR (response_status BETWEEN 200 AND 299 AND response_body IS NOT NULL))
);
