create table product (
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    price    bigint       not null check (price >= 0),
    stock    bigint       not null check (stock >= 0),
    reserved bigint       not null default 0,
    constraint product_reserved_range check (reserved >= 0 and reserved <= stock)
);

create table coupon (
    id                  bigint generated by default as identity primary key,
    code                varchar(100) not null unique,
    coupon_type         varchar(20)  not null,
    discount_value      bigint       not null,
    min_order_amount    bigint       not null default 0,
    max_discount_amount bigint,
    total_quantity      bigint       not null check (total_quantity >= 0),
    used_count          bigint       not null default 0,
    valid_from          timestamptz  not null,
    valid_until         timestamptz  not null,
    constraint coupon_used_range check (used_count >= 0 and used_count <= total_quantity)
);

create table orders (
    id              bigint generated by default as identity primary key,
    user_id         varchar(100) not null,
    status          varchar(30)  not null,
    coupon_code     varchar(100),
    subtotal        bigint       not null,
    discount        bigint       not null,
    total_price     bigint       not null,
    created_at      timestamptz  not null,
    expires_at      timestamptz  not null,
    paid_at         timestamptz,
    payment_id      varchar(100),
    payment_key     varchar(255),
    idempotency_key varchar(255),
    request_hash    varchar(64)
);

create unique index orders_user_idem_uk on orders (user_id, idempotency_key) where idempotency_key is not null;
create index orders_user_id_idx on orders (user_id, id desc);
create index orders_status_id_idx on orders (status, id desc);
create index orders_pending_expiry_idx on orders (expires_at) where status = 'PENDING_PAYMENT';

create table order_item (
    id         bigint generated by default as identity primary key,
    order_id   bigint  not null references orders (id),
    product_id bigint  not null references product (id),
    quantity   bigint  not null check (quantity > 0),
    unit_price bigint  not null
);

create index order_item_order_idx on order_item (order_id);
