-- V1__create_product_order_tables.sql
-- 주문(Order) + 재고 차감: products, orders, order_items

CREATE TABLE products (
    id     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(255) NOT NULL,
    price  BIGINT       NOT NULL,
    stock  INTEGER      NOT NULL,
    CONSTRAINT pk_products                    PRIMARY KEY (id),
    CONSTRAINT ck_products_name_not_blank     CHECK (btrim(name) <> ''),
    CONSTRAINT ck_products_price_positive     CHECK (price > 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0)
);

CREATE TABLE orders (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    status      VARCHAR(20) NOT NULL,
    total_price BIGINT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_orders                      PRIMARY KEY (id),
    CONSTRAINT ck_orders_status               CHECK (status IN ('ORDERED', 'CANCELLED')),
    CONSTRAINT ck_orders_total_price_positive CHECK (total_price > 0)
);

-- R6 목록: ORDER BY created_at DESC, id DESC
CREATE INDEX idx_orders_created_at_id ON orders (created_at DESC, id DESC);

CREATE TABLE order_items (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    order_id   BIGINT  NOT NULL,
    product_id BIGINT  NOT NULL,
    quantity   INTEGER NOT NULL,
    unit_price BIGINT  NOT NULL,
    CONSTRAINT pk_order_items                     PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order               FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product             FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_order_items_order_product       UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity_positive   CHECK (quantity >= 1),
    CONSTRAINT ck_order_items_unit_price_positive CHECK (unit_price > 0)
);
