-- V1__init.sql — order-payment 초기 스키마
-- 금액 BIGINT(C1), 시각 TIMESTAMPTZ(C2). 제약 이름은 예외 매핑(01_api_design.md §11.2)에 쓰이므로 바꾸지 말 것.

-- ---------------------------------------------------------------------------
-- products
-- ---------------------------------------------------------------------------
CREATE TABLE products (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(100) NOT NULL,
    price       BIGINT       NOT NULL,
    stock       INTEGER      NOT NULL,
    reserved    INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_products                 PRIMARY KEY (id),
    CONSTRAINT ck_products_name_not_blank  CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_products_price_range     CHECK (price BETWEEN 1 AND 10000000),
    CONSTRAINT ck_products_stock_nonneg    CHECK (stock >= 0),
    CONSTRAINT ck_products_reserved_range  CHECK (reserved >= 0 AND reserved <= stock)
);

-- ---------------------------------------------------------------------------
-- coupons
-- ---------------------------------------------------------------------------
CREATE TABLE coupons (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(20)  NOT NULL,
    discount_type        VARCHAR(10)  NOT NULL,
    discount_value       BIGINT       NOT NULL,
    min_order_amount     BIGINT       NOT NULL DEFAULT 0,
    max_discount_amount  BIGINT,
    total_quantity       BIGINT       NOT NULL,
    used_count           BIGINT       NOT NULL DEFAULT 0,
    valid_from           TIMESTAMPTZ  NOT NULL,
    valid_until          TIMESTAMPTZ  NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_coupons                      PRIMARY KEY (id),
    CONSTRAINT uk_coupons_code                 UNIQUE (code),
    CONSTRAINT ck_coupons_code_format          CHECK (code ~ '^[A-Z0-9]{4,20}$'),
    CONSTRAINT ck_coupons_discount_type        CHECK (discount_type IN ('FIXED', 'RATE')),
    CONSTRAINT ck_coupons_discount_value       CHECK (discount_value >= 1
                                                      AND (discount_type <> 'RATE' OR discount_value <= 100)),
    CONSTRAINT ck_coupons_min_order_amount     CHECK (min_order_amount >= 0),
    CONSTRAINT ck_coupons_max_discount_amount  CHECK (max_discount_amount IS NULL OR max_discount_amount >= 1),
    CONSTRAINT ck_coupons_total_quantity       CHECK (total_quantity >= 1),
    CONSTRAINT ck_coupons_used_count           CHECK (used_count >= 0 AND used_count <= total_quantity),
    CONSTRAINT ck_coupons_validity             CHECK (valid_from < valid_until)
);

-- ---------------------------------------------------------------------------
-- orders
-- ---------------------------------------------------------------------------
CREATE TABLE orders (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id      VARCHAR(50)  NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    coupon_code  VARCHAR(20),
    subtotal     BIGINT       NOT NULL,
    discount     BIGINT       NOT NULL,
    total_price  BIGINT       NOT NULL,
    payment_id   VARCHAR(255),
    created_at   TIMESTAMPTZ  NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    paid_at      TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_orders                          PRIMARY KEY (id),
    CONSTRAINT fk_orders_coupon_code              FOREIGN KEY (coupon_code) REFERENCES coupons (code),
    CONSTRAINT ck_orders_user_id_not_blank        CHECK (length(btrim(user_id)) > 0),
    CONSTRAINT ck_orders_status                   CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED',
                                                                    'EXPIRED', 'CANCELLED', 'SHIPPED',
                                                                    'DELIVERED', 'REFUNDED')),
    CONSTRAINT ck_orders_amounts                  CHECK (subtotal >= 1
                                                         AND discount >= 0
                                                         AND discount <= subtotal
                                                         AND total_price = subtotal - discount),
    CONSTRAINT ck_orders_discount_requires_coupon CHECK (coupon_code IS NOT NULL OR discount = 0),
    CONSTRAINT ck_orders_expires_after_created    CHECK (expires_at > created_at),
    CONSTRAINT ck_orders_paid_at                  CHECK ((paid_at IS NOT NULL)
                                                         = (status IN ('PAID', 'SHIPPED', 'DELIVERED', 'REFUNDED')))
);

-- 목록 키셋 정렬 (R9.4 / R9.5)
CREATE INDEX ix_orders_created_id        ON orders (created_at DESC, id DESC);
CREATE INDEX ix_orders_user_created_id   ON orders (user_id, created_at DESC, id DESC);
CREATE INDEX ix_orders_status_created_id ON orders (status, created_at DESC, id DESC);

-- 만료 스캔 (R6)
CREATE INDEX ix_orders_pending_expires   ON orders (expires_at)
    WHERE status = 'PENDING_PAYMENT';

-- 사용자별 쿠폰 활성 사용 유일성 (R2.5 / R2.6 / R10.3)
CREATE UNIQUE INDEX ux_orders_active_coupon_user ON orders (coupon_code, user_id)
    WHERE coupon_code IS NOT NULL
      AND status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED');

-- ---------------------------------------------------------------------------
-- order_items
-- ---------------------------------------------------------------------------
CREATE TABLE order_items (
    order_id    BIGINT   NOT NULL,
    line_no     INTEGER  NOT NULL,
    product_id  BIGINT   NOT NULL,
    quantity    INTEGER  NOT NULL,
    unit_price  BIGINT   NOT NULL,
    CONSTRAINT pk_order_items                PRIMARY KEY (order_id, line_no),
    CONSTRAINT fk_order_items_order          FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_order_items_order_product  UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_line_no        CHECK (line_no BETWEEN 0 AND 19),
    CONSTRAINT ck_order_items_quantity       CHECK (quantity BETWEEN 1 AND 1000),
    CONSTRAINT ck_order_items_unit_price     CHECK (unit_price >= 1)
);

CREATE INDEX ix_order_items_product_id ON order_items (product_id);

-- ---------------------------------------------------------------------------
-- idempotency_records (R4)
-- ---------------------------------------------------------------------------
CREATE TABLE idempotency_records (
    id                   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    scope                VARCHAR(20)   NOT NULL,
    idempotency_key      VARCHAR(64)   NOT NULL,
    request_fingerprint  VARCHAR(64)   NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    response_status      INTEGER,
    response_body        TEXT,
    response_location    VARCHAR(255),
    created_at           TIMESTAMPTZ   NOT NULL,
    completed_at         TIMESTAMPTZ,
    CONSTRAINT pk_idempotency_records          PRIMARY KEY (id),
    CONSTRAINT uk_idempotency_scope_key        UNIQUE (scope, idempotency_key),
    CONSTRAINT ck_idempotency_scope            CHECK (scope IN ('ORDER_CREATE', 'ORDER_PAY')),
    CONSTRAINT ck_idempotency_status           CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_idempotency_response_status  CHECK (response_status IS NULL OR response_status BETWEEN 200 AND 299),
    CONSTRAINT ck_idempotency_completed        CHECK ((status = 'COMPLETED')
                                                      = (response_status IS NOT NULL
                                                         AND response_body IS NOT NULL
                                                         AND completed_at IS NOT NULL))
);
