-- ===== products =====
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    price       BIGINT       NOT NULL,
    stock       BIGINT       NOT NULL,
    reserved    BIGINT       NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT ck_products_name     CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_products_price    CHECK (price BETWEEN 1 AND 10000000),
    CONSTRAINT ck_products_stock    CHECK (stock >= 0),
    CONSTRAINT ck_products_reserved CHECK (reserved >= 0 AND reserved <= stock)
);

-- ===== coupons =====
CREATE TABLE coupons (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(20)  NOT NULL,
    type                 VARCHAR(5)   NOT NULL,
    value                BIGINT       NOT NULL,
    min_order_amount     BIGINT       NOT NULL DEFAULT 0,
    max_discount_amount  BIGINT,
    total_quantity       BIGINT       NOT NULL,
    used_count           BIGINT       NOT NULL DEFAULT 0,
    valid_from           TIMESTAMPTZ  NOT NULL,
    valid_until          TIMESTAMPTZ  NOT NULL,
    created_at           TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_coupons_code        UNIQUE (code),
    CONSTRAINT ck_coupons_code        CHECK (code ~ '^[A-Z0-9]{4,20}$'),
    CONSTRAINT ck_coupons_type        CHECK (type IN ('FIXED', 'RATE')),
    CONSTRAINT ck_coupons_value       CHECK ((type = 'FIXED' AND value >= 1)
                                          OR (type = 'RATE'  AND value BETWEEN 1 AND 100)),
    CONSTRAINT ck_coupons_min_order   CHECK (min_order_amount >= 0),
    CONSTRAINT ck_coupons_max_disc    CHECK (max_discount_amount IS NULL OR max_discount_amount >= 1),
    CONSTRAINT ck_coupons_total       CHECK (total_quantity >= 1),
    CONSTRAINT ck_coupons_used        CHECK (used_count >= 0 AND used_count <= total_quantity),
    CONSTRAINT ck_coupons_period      CHECK (valid_from < valid_until)
);

-- ===== orders =====
CREATE TABLE orders (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  VARCHAR(50)  NOT NULL,
    status                   VARCHAR(20)  NOT NULL,
    coupon_id                BIGINT       REFERENCES coupons (id),
    coupon_code              VARCHAR(20),                       -- 응답용 비정규화(쿠폰은 불변), 목록 조인 제거
    subtotal                 BIGINT       NOT NULL,
    discount                 BIGINT       NOT NULL,
    total_price              BIGINT       NOT NULL,
    created_at               TIMESTAMPTZ  NOT NULL,
    expires_at               TIMESTAMPTZ  NOT NULL,
    paid_at                  TIMESTAMPTZ,
    payment_id               VARCHAR(100),                      -- PG paymentId (환불 호출용). 외부 비노출
    gateway_call_started_at  TIMESTAMPTZ,                       -- PG 결제/환불 호출 진행 표지 (NULL=없음). 외부 비노출
    CONSTRAINT ck_orders_status   CHECK (status IN ('PENDING_PAYMENT','PAID','SHIPPED','DELIVERED',
                                                    'PAYMENT_FAILED','EXPIRED','CANCELLED','REFUNDED')),
    CONSTRAINT ck_orders_amounts  CHECK (subtotal >= 0 AND discount >= 0 AND discount <= subtotal
                                         AND total_price = subtotal - discount),
    CONSTRAINT ck_orders_coupon   CHECK ((coupon_id IS NULL) = (coupon_code IS NULL)),
    CONSTRAINT ck_orders_expiry   CHECK (expires_at >= created_at),
    CONSTRAINT ck_orders_paid_at  CHECK ((status IN ('PAID','SHIPPED','DELIVERED','REFUNDED')) = (paid_at IS NOT NULL))
);

-- 같은 사용자가 같은 쿠폰을 "사용 중"(활성 상태) 주문으로 두 개 가질 수 없다. 상태가 복원 상태로 바뀌면 인덱스에서 자동 제외.
CREATE UNIQUE INDEX uq_orders_active_coupon_user
    ON orders (coupon_id, user_id)
    WHERE coupon_id IS NOT NULL
      AND status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED');

-- 목록 (키셋) — 필터 조합별
CREATE INDEX idx_orders_created_id        ON orders (created_at DESC, id DESC);
CREATE INDEX idx_orders_user_created_id   ON orders (user_id,  created_at DESC, id DESC);
CREATE INDEX idx_orders_status_created_id ON orders (status,   created_at DESC, id DESC);

-- 만료 스위퍼 / 지연 만료 (PENDING 행만 담는 작은 인덱스)
CREATE INDEX idx_orders_pending_expires   ON orders (expires_at) WHERE status = 'PENDING_PAYMENT';

-- ===== order_items =====
CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- 항목 순서 = 요청 순서
    order_id    BIGINT NOT NULL REFERENCES orders (id),
    product_id  BIGINT NOT NULL REFERENCES products (id),
    quantity    BIGINT NOT NULL,
    unit_price  BIGINT NOT NULL,
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity   CHECK (quantity BETWEEN 1 AND 1000),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 1)
);

-- ===== idempotency_keys =====
CREATE TABLE idempotency_keys (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    endpoint             VARCHAR(20)  NOT NULL,       -- 'ORDER_CREATE' | 'ORDER_PAY'
    idem_key             VARCHAR(64)  NOT NULL,
    request_fingerprint  VARCHAR(64)  NOT NULL,       -- SHA-256 hex (소문자 64자)
    status               VARCHAR(12)  NOT NULL,       -- 'IN_PROGRESS' | 'COMPLETED'
    attempt_id           UUID         NOT NULL,       -- 이 시도의 소유 토큰 (인수/해제/완료의 CAS 조건)
    started_at           TIMESTAMPTZ  NOT NULL,       -- IN_PROGRESS 신선도 판정 기준
    completed_at         TIMESTAMPTZ,
    response_status      INTEGER,                     -- 최초 응답 상태코드 (COMPLETED에서만)
    response_content_type VARCHAR(100),
    response_location    VARCHAR(255),
    response_body        TEXT,                        -- 최초 응답 본문 문자열 그대로 (재생용)
    CONSTRAINT uq_idem_endpoint_key  UNIQUE (endpoint, idem_key),
    CONSTRAINT ck_idem_endpoint      CHECK (endpoint IN ('ORDER_CREATE', 'ORDER_PAY')),
    CONSTRAINT ck_idem_status        CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_idem_completed     CHECK ((status = 'COMPLETED') = (response_status IS NOT NULL AND response_body IS NOT NULL))
);
