-- 회원 테이블. 이메일은 유니크 제약으로 DB 레벨에서도 중복을 막는다.
CREATE TABLE members (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    nickname   VARCHAR(30)  NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_members_email UNIQUE (email)
);
