-- V1__init.sql : order-payment 초기 스키마

CREATE TABLE products (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar(100) NOT NULL,
    price       bigint       NOT NULL,
    stock       integer      NOT NULL,
    reserved    integer      NOT NULL DEFAULT 0,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_products_price    CHECK (price BETWEEN 1 AND 10000000),
    CONSTRAINT ck_products_stock    CHECK (stock >= 0),
    CONSTRAINT ck_products_reserved CHECK (reserved >= 0 AND reserved <= stock)
);

CREATE TABLE coupons (
    id                   bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 varchar(20) NOT NULL,
    type                 varchar(10) NOT NULL,
    value                bigint      NOT NULL,
    min_order_amount     bigint      NOT NULL DEFAULT 0,
    max_discount_amount  bigint,
    total_quantity       bigint      NOT NULL,
    used_count           bigint      NOT NULL DEFAULT 0,
    valid_from           timestamptz NOT NULL,
    valid_until          timestamptz NOT NULL,
    created_at           timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_coupons_code           UNIQUE (code),
    CONSTRAINT ck_coupons_type           CHECK (type IN ('FIXED', 'RATE')),
    CONSTRAINT ck_coupons_value          CHECK (value >= 1 AND (type <> 'RATE' OR value <= 100)),
    CONSTRAINT ck_coupons_min_order      CHECK (min_order_amount >= 0),
    CONSTRAINT ck_coupons_max_discount   CHECK (max_discount_amount IS NULL OR max_discount_amount >= 1),
    CONSTRAINT ck_coupons_total_quantity CHECK (total_quantity >= 1),
    CONSTRAINT ck_coupons_used_count     CHECK (used_count >= 0 AND used_count <= total_quantity),
    CONSTRAINT ck_coupons_validity       CHECK (valid_from < valid_until)
);

CREATE TABLE orders (
    id           bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      varchar(50)  NOT NULL,
    status       varchar(20)  NOT NULL,
    coupon_code  varchar(20),
    subtotal     bigint       NOT NULL,
    discount     bigint       NOT NULL,
    total_price  bigint       NOT NULL,
    payment_id   varchar(255),
    created_at   timestamptz  NOT NULL,
    expires_at   timestamptz  NOT NULL,
    paid_at      timestamptz,
    CONSTRAINT fk_orders_coupon  FOREIGN KEY (coupon_code) REFERENCES coupons (code),
    CONSTRAINT ck_orders_status  CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED',
                                                   'PAYMENT_FAILED', 'EXPIRED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT ck_orders_amounts CHECK (subtotal >= 0 AND discount >= 0 AND discount <= subtotal
                                        AND total_price = subtotal - discount),
    CONSTRAINT ck_orders_expires CHECK (expires_at >= created_at)
);

CREATE INDEX ix_orders_created         ON orders (created_at DESC, id DESC);
CREATE INDEX ix_orders_user_created    ON orders (user_id, created_at DESC, id DESC);
CREATE INDEX ix_orders_status_created  ON orders (status, created_at DESC, id DESC);
CREATE INDEX ix_orders_pending_expires ON orders (expires_at) WHERE status = 'PENDING_PAYMENT';
CREATE INDEX ix_orders_coupon_code     ON orders (coupon_code);
CREATE UNIQUE INDEX ux_orders_active_user_coupon
    ON orders (user_id, coupon_code)
    WHERE coupon_code IS NOT NULL
      AND status IN ('PENDING_PAYMENT', 'PAID', 'SHIPPED', 'DELIVERED');

CREATE TABLE order_items (
    id          bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    bigint  NOT NULL,
    line_no     integer NOT NULL,
    product_id  bigint  NOT NULL,
    quantity    integer NOT NULL,
    unit_price  bigint  NOT NULL,
    CONSTRAINT fk_order_items_order         FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product       FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT uq_order_items_order_line    UNIQUE (order_id, line_no),
    CONSTRAINT ck_order_items_quantity      CHECK (quantity BETWEEN 1 AND 1000),
    CONSTRAINT ck_order_items_unit_price    CHECK (unit_price >= 1)
);

CREATE INDEX ix_order_items_product ON order_items (product_id);

CREATE TABLE idempotency_keys (
    id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope              varchar(20)  NOT NULL,
    idem_key           varchar(64)  NOT NULL,
    request_hash       varchar(64)  NOT NULL,
    status             varchar(20)  NOT NULL,
    response_status    integer,
    response_body      text,
    response_location  varchar(255),
    created_at         timestamptz  NOT NULL DEFAULT now(),
    completed_at       timestamptz,
    CONSTRAINT uq_idempotency_scope_key UNIQUE (scope, idem_key),
    CONSTRAINT ck_idempotency_scope     CHECK (scope IN ('ORDER_CREATE', 'ORDER_PAY')),
    CONSTRAINT ck_idempotency_status    CHECK (status IN ('IN_PROGRESS', 'COMPLETED')),
    CONSTRAINT ck_idempotency_completed CHECK (status <> 'COMPLETED'
                                               OR (response_status IS NOT NULL AND response_body IS NOT NULL))
);
