CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    price       BIGINT       NOT NULL,
    stock       INTEGER      NOT NULL,
    reserved    INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL,
    updated_at  TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_products          PRIMARY KEY (id),
    CONSTRAINT ck_products_price    CHECK (price >= 0),
    CONSTRAINT ck_products_stock    CHECK (stock >= 0),
    CONSTRAINT ck_products_reserved CHECK (reserved >= 0 AND reserved <= stock)
);

CREATE TABLE coupons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(64)  NOT NULL,
    type                VARCHAR(10)  NOT NULL,
    value               BIGINT       NOT NULL,
    min_order_amount    BIGINT       NOT NULL DEFAULT 0,
    max_discount_amount BIGINT,
    total_quantity      INTEGER      NOT NULL,
    used_count          INTEGER      NOT NULL DEFAULT 0,
    valid_from          TIMESTAMPTZ  NOT NULL,
    valid_until         TIMESTAMPTZ  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_coupons            PRIMARY KEY (id),
    CONSTRAINT uk_coupons_code       UNIQUE (code),
    CONSTRAINT ck_coupons_type       CHECK (type IN ('FIXED', 'RATE')),
    CONSTRAINT ck_coupons_value      CHECK (value > 0 AND (type <> 'RATE' OR value <= 100)),
    CONSTRAINT ck_coupons_min_order  CHECK (min_order_amount >= 0),
    CONSTRAINT ck_coupons_max_disc   CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0),
    CONSTRAINT ck_coupons_total      CHECK (total_quantity >= 1),
    CONSTRAINT ck_coupons_used       CHECK (used_count >= 0 AND used_count <= total_quantity),
    CONSTRAINT ck_coupons_period     CHECK (valid_from < valid_until)
);
