CREATE TABLE orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id          VARCHAR(64)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    coupon_id        BIGINT,
    coupon_code      VARCHAR(64),
    subtotal         BIGINT       NOT NULL,
    discount         BIGINT       NOT NULL DEFAULT 0,
    total_price      BIGINT       NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_hash     VARCHAR(64)  NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL,
    expires_at       TIMESTAMPTZ  NOT NULL,
    paid_at          TIMESTAMPTZ,
    shipped_at       TIMESTAMPTZ,
    delivered_at     TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ  NOT NULL,
    lease_kind       VARCHAR(10),
    lease_token      UUID,
    lease_expires_at TIMESTAMPTZ,
    version          BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT fk_orders_coupon FOREIGN KEY (coupon_id) REFERENCES coupons (id),
    CONSTRAINT uk_orders_user_idem UNIQUE (user_id, idempotency_key),
    CONSTRAINT ck_orders_status CHECK (status IN
        ('PENDING_PAYMENT','PAID','PAYMENT_FAILED','EXPIRED','CANCELLED','REFUNDED','SHIPPED','DELIVERED')),
    CONSTRAINT ck_orders_amounts CHECK (
        subtotal >= 0 AND discount >= 0 AND discount <= subtotal AND total_price = subtotal - discount),
    CONSTRAINT ck_orders_coupon_pair CHECK (
        (coupon_id IS NULL AND coupon_code IS NULL AND discount = 0)
        OR (coupon_id IS NOT NULL AND coupon_code IS NOT NULL)),
    CONSTRAINT ck_orders_paid_at CHECK (
        status NOT IN ('PAID','SHIPPED','DELIVERED','REFUNDED') OR paid_at IS NOT NULL),
    CONSTRAINT ck_orders_lease CHECK (
        (lease_kind IS NULL AND lease_token IS NULL AND lease_expires_at IS NULL)
        OR (lease_kind IN ('PAY','REFUND') AND lease_token IS NOT NULL AND lease_expires_at IS NOT NULL))
);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id    BIGINT  NOT NULL,
    line_no     INTEGER NOT NULL,
    product_id  BIGINT  NOT NULL,
    quantity    INTEGER NOT NULL,
    unit_price  BIGINT  NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uk_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT uk_order_items_order_line    UNIQUE (order_id, line_no),
    CONSTRAINT ck_order_items_quantity   CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price CHECK (unit_price >= 0)
);

CREATE INDEX idx_orders_user_status_id ON orders (user_id, status, id DESC);
CREATE INDEX idx_orders_user_id        ON orders (user_id, id DESC);
CREATE INDEX idx_orders_status_id      ON orders (status, id DESC);
CREATE INDEX idx_orders_pending_expiry ON orders (expires_at) WHERE status = 'PENDING_PAYMENT';
CREATE INDEX idx_order_items_product   ON order_items (product_id);
CREATE INDEX idx_orders_coupon         ON orders (coupon_id) WHERE coupon_id IS NOT NULL;
