CREATE TABLE payments (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id         BIGINT       NOT NULL,
    idempotency_key  VARCHAR(128) NOT NULL,
    request_hash     VARCHAR(64)  NOT NULL,
    amount           BIGINT       NOT NULL,
    status           VARCHAR(12)  NOT NULL,
    pg_payment_id    VARCHAR(128),
    attempt_count    INTEGER      NOT NULL DEFAULT 1,
    last_error       VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL,
    updated_at       TIMESTAMPTZ  NOT NULL,
    decided_at       TIMESTAMPTZ,
    refunded_at      TIMESTAMPTZ,
    CONSTRAINT pk_payments PRIMARY KEY (id),
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT uk_payments_order UNIQUE (order_id),
    CONSTRAINT ck_payments_status CHECK (status IN ('INITIATED','APPROVED','DECLINED','REFUNDED')),
    CONSTRAINT ck_payments_amount CHECK (amount >= 0),
    CONSTRAINT ck_payments_attempt CHECK (attempt_count >= 1),
    CONSTRAINT ck_payments_pgid CHECK (status NOT IN ('APPROVED','REFUNDED') OR pg_payment_id IS NOT NULL)
);
CREATE UNIQUE INDEX uk_payments_pg_payment_id ON payments (pg_payment_id) WHERE pg_payment_id IS NOT NULL;
