-- V1__create_products.sql
-- 상품(Product) 테이블. 필드 ↔ 컬럼 / 제약 ↔ 상태코드 정합은 01_api_design.md §5 참조.

CREATE TABLE products (
    id     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(255) NOT NULL,
    price  BIGINT       NOT NULL,
    stock  INTEGER      NOT NULL,

    CONSTRAINT pk_products
        PRIMARY KEY (id),

    -- @NotBlank보다 느슨해야 한다: ASCII 공백 6종(SP, TAB, LF, VT, FF, CR)만 제거 후 비었는지 검사.
    -- 6종 모두 Java Character.isWhitespace == true 이므로 @NotBlank 통과 값은 항상 이 CHECK도 통과.
    CONSTRAINT ck_products_name_not_blank
        CHECK (btrim(name, E' \t\n\x0B\f\r') <> ''),

    CONSTRAINT ck_products_price_positive
        CHECK (price > 0),

    CONSTRAINT ck_products_stock_non_negative
        CHECK (stock >= 0)
);

COMMENT ON TABLE  products       IS '상품';
COMMENT ON COLUMN products.id    IS '상품 id (IDENTITY)';
COMMENT ON COLUMN products.name  IS '상품명 (공백만 불가, trim 없이 저장)';
COMMENT ON COLUMN products.price IS '판매가, 원 단위 정수 (> 0)';
COMMENT ON COLUMN products.stock IS '재고 수량 (>= 0)';
