-- V1__create_order_schema.sql
-- 상품, 주문, 주문 항목. 금액은 원 단위 정수(bigint), 수량/재고는 integer.

CREATE TABLE products (
    id     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(255) NOT NULL,
    price  BIGINT       NOT NULL,
    stock  INTEGER      NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT ck_products_name_not_blank     CHECK (btrim(name) <> ''),
    CONSTRAINT ck_products_price_positive     CHECK (price > 0),
    CONSTRAINT ck_products_stock_non_negative CHECK (stock >= 0)
);

CREATE TABLE orders (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    status      VARCHAR(20) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id),
    CONSTRAINT ck_orders_status CHECK (status IN ('ORDERED', 'CANCELLED'))
);

-- R6 목록: ORDER BY created_at DESC, id DESC
CREATE INDEX ix_orders_created_at_id ON orders (created_at DESC, id DESC);

CREATE TABLE order_items (
    id          BIGINT  GENERATED BY DEFAULT AS IDENTITY,
    order_id    BIGINT  NOT NULL,
    product_id  BIGINT  NOT NULL,
    quantity    INTEGER NOT NULL,
    unit_price  BIGINT  NOT NULL,
    CONSTRAINT pk_order_items PRIMARY KEY (id),
    CONSTRAINT fk_order_items_order   FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id),
    -- 선두 컬럼 order_id: 주문별 항목 로딩 인덱스 역할도 겸한다
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity_positive   CHECK (quantity >= 1),
    CONSTRAINT ck_order_items_unit_price_positive CHECK (unit_price > 0)
);
