create table products (
    id       bigint generated by default as identity primary key,
    name     varchar(100) not null,
    price    bigint       not null check (price between 1 and 10000000),
    stock    integer      not null check (stock >= 0),
    reserved integer      not null default 0 check (reserved >= 0 and reserved <= stock)
);

create table coupons (
    id                  bigint generated by default as identity primary key,
    code                varchar(20) not null unique,
    type                varchar(10) not null check (type in ('FIXED', 'RATE')),
    discount_value      bigint      not null check (discount_value >= 1),
    min_order_amount    bigint      not null default 0 check (min_order_amount >= 0),
    max_discount_amount bigint check (max_discount_amount >= 1),
    total_quantity      integer     not null check (total_quantity >= 1),
    used_count          integer     not null default 0 check (used_count between 0 and total_quantity),
    valid_from          timestamptz not null,
    valid_until         timestamptz not null,
    check (valid_from < valid_until)
);

create table orders (
    id          bigint generated by default as identity primary key,
    user_id     varchar(50)  not null,
    status      varchar(20)  not null check (status in ('PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED', 'EXPIRED',
                                                       'CANCELLED', 'SHIPPED', 'DELIVERED', 'REFUNDED')),
    coupon_code varchar(20) references coupons (code),
    subtotal    bigint       not null,
    discount    bigint       not null,
    total_price bigint       not null,
    created_at  timestamptz  not null,
    expires_at  timestamptz  not null,
    paid_at     timestamptz,
    payment_id  varchar(100)
);

create index idx_orders_created on orders (created_at desc, id desc);
create index idx_orders_user_created on orders (user_id, created_at desc, id desc);
create index idx_orders_coupon_user on orders (coupon_code, user_id) where coupon_code is not null;
create index idx_orders_pending_expiry on orders (expires_at) where status = 'PENDING_PAYMENT';

create table order_items (
    id         bigint generated by default as identity primary key,
    order_id   bigint  not null references orders (id),
    product_id bigint  not null references products (id),
    quantity   integer not null check (quantity between 1 and 1000),
    unit_price bigint  not null
);

create index idx_order_items_order on order_items (order_id);

create table idempotency_records (
    scope           varchar(20)  not null,
    idem_key        varchar(64)  not null,
    fingerprint     varchar(64)  not null,
    status          varchar(20)  not null check (status in ('IN_PROGRESS', 'COMPLETED')),
    response_status integer,
    response_body   text,
    location        text,
    created_at      timestamptz  not null default now(),
    primary key (scope, idem_key)
);
