-- V1__init_schema.sql : order-payment 초기 스키마

CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    price       BIGINT       NOT NULL,
    stock       INTEGER      NOT NULL,
    reserved    INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_products_name_not_blank   CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_products_price            CHECK (price >= 0),
    CONSTRAINT ck_products_stock            CHECK (stock >= 0),
    CONSTRAINT ck_products_reserved         CHECK (reserved >= 0),
    CONSTRAINT ck_products_reserved_le_stock CHECK (reserved <= stock)
);

CREATE TABLE coupons (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                VARCHAR(50)  NOT NULL,
    coupon_type         VARCHAR(10)  NOT NULL,
    discount_value      BIGINT       NOT NULL,
    min_order_amount    BIGINT       NOT NULL DEFAULT 0,
    max_discount_amount BIGINT,
    total_quantity      INTEGER      NOT NULL,
    used_count          INTEGER      NOT NULL DEFAULT 0,
    valid_from          TIMESTAMPTZ  NOT NULL,
    valid_until         TIMESTAMPTZ  NOT NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_coupons_code            UNIQUE (code),
    CONSTRAINT ck_coupons_type            CHECK (coupon_type IN ('FIXED', 'RATE')),
    CONSTRAINT ck_coupons_value           CHECK (discount_value > 0),
    CONSTRAINT ck_coupons_rate_range      CHECK (coupon_type <> 'RATE' OR discount_value BETWEEN 1 AND 100),
    CONSTRAINT ck_coupons_min_order       CHECK (min_order_amount >= 0),
    CONSTRAINT ck_coupons_max_discount    CHECK (max_discount_amount IS NULL OR max_discount_amount > 0),
    CONSTRAINT ck_coupons_total_quantity  CHECK (total_quantity >= 1),
    CONSTRAINT ck_coupons_used_le_total   CHECK (used_count >= 0 AND used_count <= total_quantity),
    CONSTRAINT ck_coupons_valid_period    CHECK (valid_from < valid_until)
);

CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      VARCHAR(64)  NOT NULL,
    status       VARCHAR(20)  NOT NULL,
    coupon_code  VARCHAR(50),
    subtotal     BIGINT       NOT NULL,
    discount     BIGINT       NOT NULL DEFAULT 0,
    total_price  BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    expires_at   TIMESTAMPTZ  NOT NULL,
    paid_at      TIMESTAMPTZ,
    updated_at   TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_orders_coupon        FOREIGN KEY (coupon_code) REFERENCES coupons (code),
    CONSTRAINT ck_orders_status        CHECK (status IN ('PENDING_PAYMENT', 'PAID', 'PAYMENT_FAILED', 'EXPIRED',
                                                         'CANCELLED', 'REFUNDED', 'SHIPPED', 'DELIVERED')),
    CONSTRAINT ck_orders_amounts       CHECK (subtotal >= 0 AND discount >= 0 AND discount <= subtotal
                                              AND total_price = subtotal - discount),
    CONSTRAINT ck_orders_expiry        CHECK (expires_at > created_at),
    CONSTRAINT ck_orders_paid_at       CHECK (
        (status IN ('PENDING_PAYMENT', 'PAYMENT_FAILED', 'EXPIRED', 'CANCELLED') AND paid_at IS NULL)
        OR (status IN ('PAID', 'SHIPPED', 'DELIVERED', 'REFUNDED') AND paid_at IS NOT NULL))
);

CREATE INDEX idx_orders_user_id_id ON orders (user_id, id DESC);
CREATE INDEX idx_orders_status_id  ON orders (status, id DESC);
CREATE INDEX idx_orders_pending_expiry ON orders (expires_at) WHERE status = 'PENDING_PAYMENT';

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT  NOT NULL,
    product_id  BIGINT  NOT NULL,
    quantity    INTEGER NOT NULL,
    unit_price  BIGINT  NOT NULL,
    CONSTRAINT fk_order_items_order    FOREIGN KEY (order_id)   REFERENCES orders (id),
    CONSTRAINT fk_order_items_product  FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_order_items_quantity CHECK (quantity > 0),
    CONSTRAINT ck_order_items_price    CHECK (unit_price >= 0)
);

CREATE TABLE payments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT       NOT NULL,
    payment_id   VARCHAR(100) NOT NULL,   -- PG가 발급한 결제 id (UNIQUE 아님: PG 스텁의 id 재사용 허용)
    status       VARCHAR(20)  NOT NULL,
    amount       BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL,
    refunded_at  TIMESTAMPTZ,
    CONSTRAINT fk_payments_order    FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT uq_payments_order    UNIQUE (order_id),
    CONSTRAINT ck_payments_status   CHECK (status IN ('APPROVED', 'DECLINED', 'REFUNDED')),
    CONSTRAINT ck_payments_amount   CHECK (amount >= 0),
    CONSTRAINT ck_payments_refunded CHECK ((status = 'REFUNDED') = (refunded_at IS NOT NULL))
);

CREATE TABLE idempotency_keys (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation     VARCHAR(20)  NOT NULL,
    scope_key     VARCHAR(64)  NOT NULL,   -- CREATE_ORDER: user_id, PAY: '*'
    idem_key      VARCHAR(128) NOT NULL,
    request_hash  VARCHAR(64)  NOT NULL,   -- SHA-256 hex
    order_id      BIGINT,
    outcome       VARCHAR(20),
    created_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uq_idempotency_scope  UNIQUE (operation, scope_key, idem_key),
    CONSTRAINT fk_idempotency_order  FOREIGN KEY (order_id) REFERENCES orders (id),
    CONSTRAINT ck_idempotency_operation CHECK (operation IN ('CREATE_ORDER', 'PAY')),
    CONSTRAINT ck_idempotency_outcome   CHECK (outcome IS NULL OR outcome IN ('CREATED', 'APPROVED', 'DECLINED'))
);
